version: '3.1'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch-lab
    environment:
      - discovery.type=single-node
      - action.auto_create_index=true
    ports:
      - '9220:9200'
      - '9330:9300'
    volumes:
      - './data/elastic:/data/elk'
    networks:
      sinapse:
        aliases:
          - elasticsearch
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    container_name: kibana-lab
    ports:
      - '5661:5601'
    volumes:
      - './data/elastic:/data/kibana'
    depends_on:
      - elasticsearch
    networks:
      sinapse:
        aliases:
          - kibana
  node-server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    container_name: node-server-lab
    ports:
      - '8001:8000'
      - '8081:8080'
    volumes:
      - './data/node-server:/data/node'
    restart: always
    networks:
      sinapse:
        aliases:
          - node-server
networks:
  sinapse: null
