version: '3.1'
services:
  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - action.auto_create_index=true
    ports:
      - '9220:9200'
      - '9330:9300'
    volumes:
      - './data/elastic:/data/elk'
    networks:
      sinapse:
        aliases:
          - elasticsearch
  kibana:
    build:
      context: ./kibana
      dockerfile: Dockerfile
    container_name: kibana
    ports:
      - '5661:5601'
    volumes:
      - './data/elastic:/data/kibana'
    depends_on:
      - elasticsearch
      - mongo
      - monstache
    networks:
      sinapse:
        aliases:
          - kibana
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    container_name: mongo
    ports:
      - '27037:27017'
    volumes:
      - './data/mongo:/data/db'
    restart: always
    networks:
      sinapse:
        aliases:
          - mongo   
  monstache:
    build:
      context: ./monstache
      dockerfile: Dockerfile
    container_name: monstache
    depends_on:
      - elasticsearch
      - mongo
    networks:
      sinapse:
        aliases:
          - monstache
networks:
  sinapse: null
